Repository NativeScript/nativescript-cloud, pull requests merged in 2019-06, with the labels that each got.

#170 fix: tables output is not correct
  lib/commands/account/account-list.ts
  lib/commands/account/features.ts
  lib/commands/account/usage.ts
  lib/services/cloud-apple-service.ts
  lib/services/cloud-build-service.ts
  lib/services/cloud-codesign-service.ts
  lib/services/cloud-project-service.ts
  lib/services/cloud-publish-service.ts
  lib/services/cloud-service.ts
Labels: bug

#171 fix: cloud build should use same bundle options as locally
  lib/services/cloud-build-service.ts
  package.json
Labels: bug, cla: yes

#169 feat: support only webpack workflow
  lib/bootstrap.ts
  lib/cloud-platforms-data.ts
  lib/commands/build-command-helper.ts
  lib/commands/cloud-deploy.ts
  lib/definitions/application-service.d.ts
  lib/definitions/build-command-helper.d.ts
  lib/definitions/cloud-build-service.d.ts
  lib/definitions/cloud-platform-service.d.ts
  lib/definitions/cloud-platforms-data.d.ts
  lib/services/application-service.ts
  lib/services/cloud-build-service.ts
  lib/services/cloud-platform-service.ts
  package.json
Labels: cla: yes

#172 fix: publish commands fail to build app
  lib/services/cloud-build-service.ts
  package.json
Labels: bug, cla: yes
